services:
  mysql:
    image: mysql:8.0
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: planit
      MYSQL_USER: planituser
      MYSQL_PASSWORD: planitpass

  app:
    build: .
    env_file: .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
