services:
  redis:
    image: redis:7.0

  app:
    image: ${DOCKERHUB_USERNAME}/planit:latest
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_PLAYGROUND_CLIENT_ID=${GOOGLE_PLAYGROUND_CLIENT_ID}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - APP_AGREEMENT_BASEURL=${APP_AGREEMENT_BASEURL}
    ports:
      - '8080:8080'
    depends_on:
      - redis