spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트용 DB 자동 생성/삭제
  sql:
    init:
      mode: never
  logging:
    level:
      root: WARN
