spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 기본 dev
    include: oauth
  data:
    redis:
      host: localhost
      port: 6379
      # 필요시 password, timeout 등 추가 가능
  jackson:
    serialization:
      write-dates-as-timestamps: false


# 공통 설정이 있다면 여기에
jwt:
  secret: your-super-secret-key-that-should-be-long-and-secure