name: '하위 작업 생성'
description: '깃허브 이슈와 지라 티켓(하위 작업)을 생성합니다'
labels: [feat]
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: '상위 작업 (Ticket Number)'
      description: '작업의 Ticket Number를 기입해주세요'
      placeholder: 'PL'
    validations:
      required: true
      
  - type: input
    id: description
    attributes:
      label: '상세 내용(Description)'
      description: '하위 작업에 대해서 간략히 설명해주세요'
    validations:
      required: true
